### ISSUE TITLE
hg38 and mm10?

### ISSUE THREAD

**Issue by AndreaGuarracino** [noise42/BRIO#10]
Is BRIO worth to offer to the scientific community more updated results?

**Comment by noise42** [comment]
Idea:
We have to process those data with the new BEAM.

Let's process it with the new BEAM (to provide hg38 and mm10 to the webserver), but **without** publishing any results

Then we will have the data already processed for the new BEAM paper.

**Comment by AndreaGuarracino** [comment]
When?

**Comment by noise42** [comment]
When Florence brings its army
