### ISSUE TITLE
What am I doing wrong with search 2.0?

### ISSUE THREAD

**Issue by AndreaGuarracino** [noise42/BRIO#11]
The command

```
python3 /home/andrea/Scrivania/BRIO/scripts/search2.0.py --input /home/andrea/Scrivania/BRIO/results/4033bb59e388e4b91cdba4f76e76190a/tmp.complete_input_with_dot_bracket_and_bear.txt --motifs /home/andrea/Scrivania/BRIO/motifs_nuc_groups/motifs_HITS_hg19_seq.txt
```
gives me this output

`
Traceback (most recent call last):
  File "/home/andrea/Scrivania/BRIO/scripts/search2.0.py", line 181, in <module>
    out = compare(to_align, motifs, read_MBR(mbr_path), bear_string, args.seqFlag)
  File "/home/andrea/Scrivania/BRIO/scripts/search2.0.py", line 123, in compare
    thr = motifs[motif]['thr']
KeyError: 'thr'
`
The command

```python3 /home/andrea/Scrivania/BRIO/scripts/search2.0.py --input /home/andrea/Scrivania/BRIO/results/4033bb59e388e4b91cdba4f76e76190a/tmp.complete_input_with_dot_bracket_and_bear.txt --motifs /home/andrea/Scrivania/BRIO/motifs_nuc_groups/motifs_HITS_hg19_seq.txt --sequence```

gives me this output

`
Traceback (most recent call last):
  File "/home/andrea/Scrivania/BRIO/scripts/search2.0.py", line 172, in <module>
    motifs = parse_motif(args.motifsFile, args.seqFlag)
  File "/home/andrea/Scrivania/BRIO/scripts/search2.0.py", line 93, in parse_motif
    thr = np.min(scores)
  File "<__array_function__ internals>", line 6, in amin
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py", line 2746, in amin
    keepdims=keepdims, initial=initial, where=where)
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
`

The input file contains the following text:

```
>chr1:149783661-149783992(-)
AGCACUUUGCGAGUCUUCAUUUGCAUACGGGCUCUAUAAGUAGCGCAUAACCAGCCCGUUUUGCGGUAGUUCGGAUUACUUCUUUAAGUCUCUUUUCUCUUUUUUCGCGCAAAAAUGCCGGAUCCAGCGAAAUCCGCUCCUGCUCCCAAGAAGGGCUCCAAAAAGGCUGUUACGAAAGUGCAGAAGAAGGACGGCAAGAAGCGCAAGCGCAGCCGCAAGGAGAGCUACUCCGUUUACGUGUACAAGGUGCUGAAGCAGGUCCACCCCGACACCGGCAUCUCGUCCAAGGCCAUGGGCAUCAUGAACUCCUUCGUCAACGACAUCUUCGAGC
.(((((((..((((((............)))))).....(((((((......(((((.(((((.(((((..((((((((((....))))......((.((...((((.(((....)))))))...)).))))))))...)))))..))))).)))))........)).))))).))))))).((.((((((((((.....((....))...))))...((((.....)))).............((((((((..(..((......))..)..)))))))).(((((......))))).........)))))).))..(((.....)))...
:GGGGGGG::ffffffuuuuuuuuuuuuffffff:::::EEEEEBBOOOOOOEEEEE{EEEEE{EEEEEKKFFFFFFddddmmmmdddd::::::bb[bb"""dddd[cccmmmmcccdddd333bb]bbFFFFFFZZZEEEEEYYEEEEE}EEEEE////////BB}EEEEE}GGGGGGG:BB{FFFFFFdddd$$$$$bbmmmmbb333dddd:::ddddnnnnndddd:::::::::::::hhhhhhhh!!a!!bboooooobb22a22hhhhhhhh:eeeeeooooooeeeee:::::::::FFFFFF}BB::cccnnnnnccc:::
>chr1:149784741-149784985(-)
CUUCCAGAGCUCGGCCGUGAUGGCGCUGCAGGAGGCCAGCGAGGCCUACCUGGUGGGGCUGUUCGAAGACACGAACCUGUGCGCCAUCCAUGCCAAGCGCGUGACCAUCAUGCCCAAGGACAUCCAGUUGGCCCGCCGCAUCCGCGGGGAGCGGGCCUAAGGCAUAUUUUUAAGUGGUCGAUCUAAAGGCUCUUUUCAGAGCCACUGCCGUUUUCAUCAAGAGCAGCUGUACCGGCUCUCCAUC
.....(((((.(((..(.((((((((.(((((((.((.((.(((....))).)).)).)).((((......))))))))))))))))))((((.....))))((((((.(((((...((....))....(((((((....(((....))))))))))...)))))........))))))........((((((....))))))((.((.(((((.....))))).)).)).)))))))).....
:::::EEEEE{CCC::A{HHHHHHHH{EEEEEbb[bb[bb[cccmmmmccc]bb]bb]bb:ddddooooooddddEEEEEHHHHHHHHAddddnnnnnddddFFFFFF{EEEEE:::bbmmmmbb::::ggggggg####cccmmmmcccggggggg:::EEEEE////////FFFFFF::::::::ffffffmmmmffffffbb[bb[eeeeennnnneeeee]bb]bb:CCCEEEEE:::::

```

**Comment by noise42** [comment]
In the first case I invite you to try again now (I pushed some new things)

In the second case there were many "empty" motifs because the starting data is not clean at all. I patched it for now, but we should consider cleaning it for good (or simply wait the new data and fuck everything)

**Comment by AndreaGuarracino** [comment]
Right, the first command was already working in BRIO, here there was a invesion in the copy and paste.
