### ISSUE TITLE
Gestione errori intermedi

### ISSUE THREAD

**Issue by noise42** [noise42/BRIO#2]
Servirebbe un sistema più verboso di errori interni, magari un log (o anche solo un stderr/out) controllato. Mi continua a dare questo errore su terminale:

`stderr: Traceback (most recent call last):
  File "scripts/_completeWithDotBracketAndBEAR.py", line 178, in <module>
    path_complete_input_rna_molecules, input_rna_to_length_dict = process_input_rna_molecules(sys.argv[1], dir_user)
  **File "scripts/_completeWithDotBracketAndBEAR.py", line 135, in process_input_rna_molecules**
    universal_newlines=True
  File "/Users/marco/anaconda/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/Users/marco/anaconda/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/marco/anaconda/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/Users/marco/anaconda/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error`

e non riesco a risalire al problema a parte che sembra la chiamata a RNAfold 
linea 134:

`# Calculate dotbracket
        missing_bear_rna_molecules_added_dot_bracket = subprocess.check_output(
            [os.path.join(dir_base, 'scripts', 'RNAfold'), '--noPS', path_missing_dot_bracket_input],
            # To get strings
            universal_newlines=True
        )`

il file che me la genera è questo:
[input_RNAs.txt](https://github.com/noise42/BRIO/files/4473540/input_RNAs.txt)

per verificare se è una cosa di OS chiederei a @FraBall di provare a replicare l'errore

**Comment by AndreaGuarracino** [comment]
@FraBall, please, try it on OS.

**Comment by francescoballesio** [comment]
> @FraBall, please, try it on OS.

Got the same error on OS

**Comment by noise42** [comment]
The problem is in the fact that RNAfold is a binary from linux. The problem is therefore *limited* to unfolded inputs. I propose to ignore this and focus on the enhancement proposed up there. I'll open another issue
