### ISSUE TITLE
Caratteri non validi negli ID degli RNA

### ISSUE THREAD

**Issue by noise42** [noise42/BRIO#4]
al momento una cosa del genere:

**>chr1:149784741-149784985(-)**

da errore ^

**Comment by AndreaGuarracino** [comment]
We have a problem. I can't reproduce this issue and [this one](https://github.com/noise42/BRIO/issues/2). Please be more picky about specifying each step to reproduce the error. Or make a video!

**Comment by AndreaGuarracino** [comment]
Are you able to reproduce these issues with BRIO online too?

**Comment by noise42** [comment]
> Are you able to reproduce these issues with BRIO online too?

actually no, hope this is not another OS dependent bug - I'll try to see if the culprits could be outdated packages

**Comment by noise42** [comment]
> > Are you able to reproduce these issues with BRIO online too?
> 
> actually no, hope this is not another OS dependent bug - I'll try to see if the culprits could be outdated packages

outdated packages were not the problem.
@AndreaGuarracino is it possible to have distinct error messages depending on the errors? are we implementing that or is a thing for the future?

**Comment by noise42** [comment]
Tana
I suppose that subprocess.check_output() calls RNAfold in strange ways, still investigating

`(base) MBP-di-Marco:BRIO marco$ ./scripts/RNAfold 
-bash: ./scripts/RNAfold: cannot execute binary file
(base) MBP-di-Marco:BRIO marco$ cd scripts/
(base) MBP-di-Marco:scripts marco$ RNAfold 

Input string (upper or lower case); @ to quit
....,....1....,....2....,....3....,....4....,....5....,....6....,....7....,....8

(base) MBP-di-Marco:scripts marco$ cd ..
(base) MBP-di-Marco:BRIO marco$ exec scripts/RNAfold 
-bash: /Users/marco/BRIO/BRIO/scripts/RNAfold: cannot execute binary file
-bash: /Users/marco/BRIO/BRIO/scripts/RNAfold: Undefined error: 0`

**Comment by noise42** [comment]
Confirmed, RNAfold binary is for linux.

**Comment by noise42** [comment]
Second confirm: if I use an already "folded" input, the error does not show

**Comment by noise42** [comment]
Problem was in the population of the text-area. String input did not work well for long string with new lines. Now BRIO correctly loads the examples from files with an ajax call to public/examples/*.

I close the issue
