### ISSUE TITLE
Update the input format description

### ISSUE THREAD

**Issue by AndreaGuarracino** [noise42/BRIO#5]
After the updates to manage the FASTA files with lines of max 80 characters, the input is now processed in "blocks":
- header
- blocks of contiguous valid RNAs
- blocks of contiguous valid structures

**Comment by noise42** [comment]
I don't get it: 
does it mean that all the sequences must be before all the structures?

**Comment by AndreaGuarracino** [comment]
Yes. The first line has to be the header (>some text). The second line has to be a valid RNA sequence (ribonucleotides) that can continue in the following lines, until an other type of sequence is found. The remaining lines are optional: if they are present, then they have to be all valid secondary structure sequences (dot-brackets alphabet).

**Comment by noise42** [comment]
updated
