### ISSUE TITLE
Improve Search.jar

### ISSUE THREAD

**Issue by noise42** [noise42/BRIO#7]
@AndreaGuarracino please write here the desired behaviour of search

**Comment by AndreaGuarracino** [comment]
The search1.2.jar file takes as a file with one structural motif and one file with the input sequences. In the worst case scenario (a search on all experimental technologies and all species), I have to call this tool thousands of time for each structural motif available, and I think this is a bottleneck for the execution time.

A quick trial would be to modify the search1.2.jar to take as input a file with more motifs (not just one), to avoid to call it for each one. If it will work, we will project to group the structural motifs togheter by technologies, or by species, or by protein family, or other.

**Comment by noise42** [comment]
Search2.0.py pushed (in scripts/) 
for now:
- only works on structures
- prints the outputs on screen
- needs a reformatting of the motif file

not freely usable at the moment

**Comment by noise42** [comment]
new search is ready - both for sequence and structures

this is the helper. 

`usage: search2.0.py [-h] [--input INPUTFILE] [--motifs MOTIFSFILE]
                    [--sequence]

Look for motifs in database of motif PFMs

optional arguments:
  -h, --help            show this help message and exit
  --input INPUTFILE, -i INPUTFILE
                        input multiFasta with BEAR notation
  --motifs MOTIFSFILE, -m MOTIFSFILE
                        target motifs file
  --sequence            for running the search on sequences instead of
                        structures`

the only thing missing is:
- writing on file, waiting to decide where to write and in what format

**Comment by AndreaGuarracino** [comment]
Add an option to choose where to write (file or standard output).

**Comment by noise42** [comment]
> Add an option to choose where to write (file or standard output).

added: -o/--o \<file\> 

Default: stdout

**Comment by AndreaGuarracino** [comment]
May you explain the output format?

Before, for each motifs, the output was

for nuc
\>chr1:4771981-4772204(+)	UGA	8.91	224	71	74
\>chr10:64573513-64573723(-)	UGA	8.91	211	164	167
\>chr10:64573524-64573735(-)	UGA	8.91	212	176	179
...

for str

[INFO]Leggo sequenze query...
[INFO]Leggo file di benchmark...
[INFO]imposto lunghezza motivo...
[INFO]Carico PSSM...
[INFO]Inizio ricerca su sequenze query
[INFO]>chr1:4771981-4772204(+)
[INFO]cgggggggooooooggggggg	109	130	4.675864231382759
[INFO]>chr10:64573513-64573723(-)
[INFO]e####cccnnnnnccc4444e	30	51	2.4947317218844844
[INFO]>chr10:64573524-64573735(-)
[INFO]bb!!ddddoooooodddd22b	3	24	3.3364682540551724

and the server counted the number of score greater than a threshold to get a percentage required for the Fisher test.

**Comment by noise42** [comment]
for each sequence:
{'HITSCLIP_Nova_Zhang2011b_mm9_CDS_m1_run2.txt': (18.517768172505004, 18.081, 10, 23), 'HITSCLIP_FUS_Nakaya2013a_mm9_CDS_m2_run2.txt': (19.722080938162993, 17.1836, 8, 25),
...
--motif tested :( score , threshold for the motif , position on the sequence , motif length)

I should probably add information on the sequence in output

**Comment by AndreaGuarracino** [comment]
I think the new output should be equivalent to the old one to avoid surprises (you can look at some old output files in the old BRIO folder), unless we want to totally change the underlying algorithms.

**Comment by noise42** [comment]
Is there any script that runs on the output?

**Comment by AndreaGuarracino** [comment]
> https://github.com/noise42/BRIO/blob/master/scripts/_completeWithDotBracketAndBEAR.py

The `perc_seq_motif` function and the code after its call (you will find some SanGuarracino hybrid code, be prepared).

**Comment by noise42** [comment]
isn't it now focused on single motifs?

Like 
motif1
seq 1 match
seq2 match
seq3 match

motif2
seq 1 match
seq 2 match
etc


... should it be better to have a "sequence" centered output?

sequence 1
motif 1 match
motif 2 match
etc?

**Comment by AndreaGuarracino** [comment]
Okay, for now we can simplify this step, using directly the output of the search.
