### ISSUE TITLE
Combine old motif files

### ISSUE THREAD

**Issue by noise42** [noise42/BRIO#9]
As per #7 :

I already wrote a script (in scripts/utils/combine_motif_files.py) to combine old motif files in "filter groups".
the syntax is 

combine_motif_files.py <directoryWithMotifFiles> <seq|str> 

the output is created in the working directory so we must move it manually after creation (at most 6 files by now (3x2 filters).

Where are the oldmotifs stored? How much space do they occupy?

**Comment by AndreaGuarracino** [comment]
/motifs_str --> struct, 2666 elements, 35,6 MB
/motifs_seq --> seq, 2681 elements, 26,0 MB

**Comment by noise42** [comment]
done

`motifs_nuc_groups/`
`motifs_str_groups/`

contain the grouped files.

the original data files are .gitignored
